### ISSUE TITLE
Update the front end to make all fields send to the backend

### ISSUE THREAD

**Issue by NathanDuPont** [4201VitruvianBots/VitruvianManufacturing#12]
After we make our new endpoints in Issue #11 , we can now see the data that is being sent _to our back end_ from our front end. Let's now use this to make sure all the fields we want are getting sent to the backend. Since we now print out the data within `request.form` from the last issue, we will be able to see all the information that the front end is sending to our back-end server.

- [x] For each of the inputs in your front-end server, add a `name` attribute to your inputs. **This is the name that will show up in the backend**:

```
<input type="number" name="my_number_field" id="numberField" />
```
In this case, "my_number_field" will be sent to the backend with the data that the user entered in the field.

- [x] Make two terminals in VSCode. In the first terminal, start your front-end website. In the second terminal, start your back-end server. You now should be able to open your browser and see your app and should have the back-end server running in VSCode
- [x] Fill out all of the fields of your form with data, and hit "submit". This will send a request from your web app to the server, which should now print out the data. Make sure all of the fields you want are present! If any fields **don't** show up, then spend some time researching how to make them work in the front-end. 

As a recommendation - when you have an idea, update your front-end and save the file. Re-submit the form and see what fields show up in the backend with the updated form.

**Comment by blueskye04** [comment]
making tabs so this can work

**Comment by blueskye04** [comment]
made a new issue for tabs.
