### ISSUE TITLE
Make fields in the app required

### ISSUE THREAD

**Issue by NathanDuPont** [4201VitruvianBots/VitruvianManufacturing#15]
Currently, the app allows users to fill out data fields when they are done with a part in CAD. As the form is now, the user isn't required to fill out any specific fields - instead, it's possible for the user to submit an entirely empty form, which isn't ideal for us.

- [x] Read through this guide on how required fields work: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required
- [x] Look at each of the forms in the app, and make them "required" if the user needs to fill them out. NOTE: You can also see which forms are required on the original Google form, and make the same ones required here
- [x] Test and confirm that all the required forms need to be filled out before the data is submitted

**Comment by blueskye04** [comment]
made all fields required in the drivetrain. will be working on making different tabs.

**Comment by NathanDuPont** [comment]
Sounds good! As a hint for making tabs, you can use some of the logic from your ButtonInput here - but instead of returning a different button when `value` is 0 and 1, we can return a different `<Page>` based on either a radio button or a tab at the top of the page
