### ISSUE TITLE
Create wireframe for the Part Submission Form

### ISSUE THREAD

**Issue by NathanDuPont** [4201VitruvianBots/VitruvianManufacturing#2]
On the team, we currently have a part submission form that design uses to send their completed parts over to design. This form is located here: https://docs.google.com/forms/d/e/1FAIpQLSeXr0WSYJUKAsI0ZWtc7nY0UU04I8-dx0U7ZY80FCJycuOC6w/viewform

For our application, we want to start by copying this form and turning it into a web application (similar to the scouting app). This will allow us to change how it works, and improve it for our needs. Start your work by creating a wireframe of this application in PowerPoint/Google Slides/any other app of your choice. This wireframe should allow the user to do the following:

- [x] Click through the wireframe like they are filling out the application (text boxes and inputs don't need to work, we just want to see what all the pieces look like)
- [x] All inputs from the original form should be represented somewhere on the new wireframe

**Comment by blueskye04** [comment]
Wireframe: https://docs.google.com/presentation/d/1RWdgZGsg83UfWhVAayoDcC71iuoaIK9GbqMdHkQ4sWk/edit#slide=id.g1d702a07f73_0_48

**Comment by blueskye04** [comment]
Paths: https://docs.google.com/document/d/11uZFXKW-Bzl1tgAzr7L0GrUcPl0nMpyybCH2r3NyQP8/edit#
