### ISSUE TITLE
Create a sketch for how the existing part workflow works

### ISSUE THREAD

**Issue by NathanDuPont** [4201VitruvianBots/VitruvianManufacturing#4]
To make a useful app, it's very important to understand what problem we are trying to solve. For us, we want to make an app that manages how parts go from CAD to being manufactured. If we want to make something impactful, we need to understand what people are _trying_ to do currently, and what the current problems are occurring. 

Sketch out a diagram (either on paper or on your computer) that explains what happens to all parts of our team. Specifically, we want a diagram that looks something like the following:
![image](https://user-images.githubusercontent.com/6099416/215711884-b3dad29d-7abc-4ec7-997a-6bdc1158f478.png)

A few pieces of this diagram have already been created for you - but we really want to know what happens inside these yellow boxes. Inside each yellow box, one or more things are happening that we want our app to handle (hint: it's likely more than one). Follow these steps to help us figure out the part workflow:
- [x] Write/draw what happens to a part between a designer submitting a part model (first green box) and the part being machined (first yellow box). What are all of the steps that the part travels through? Where is the part/information shown to people throughout this process? Does anyone need to approve parts here?
- [x] Write/draw what happens to a part between a machinist creating the part, and the part being put on the robot. Where does the part get put after it is machined? Who's job is to assemble the part on the robot?

This will help us get a much better idea of _how_ our robot gets made, as well as how we can _improve_ this process. NOTE: This diagram is VERY important to us, and we will keep adding to it throughout our project!

**Comment by blueskye04** [comment]
https://docs.google.com/presentation/d/1E3HVFsCIE4sBEOJ_gpZN-yguwtCv_7I6oV7h0SeinXU/edit?usp=sharing
