### ISSUE TITLE
Create a basic Flask backend server

### ISSUE THREAD

**Issue by NathanDuPont** [4201VitruvianBots/VitruvianManufacturing#8]
For our application to store and use data, we will need some type of backend server. Our scouting app uses a backend server called Flask, which is a python-based server that allows you to easily handle sending and receiving data from web applications. For our web app, we will also be using Flask to store our data and send it to a web app for machining to use.

- [x] Check if you have python installed (run `python --version` in your terminal; if nothing shows up, send a message to Nathan)
- [x] Read through this guide on using python: https://developer.fedoraproject.org/tech/languages/python/python-installation.html
- [x] Watch and follow along to this video to create a very simple flask app: https://www.youtube.com/watch?v=6M3LzGmIAso&ab_channel=S3CloudHub
     - While watching the video, make the same files within the `Backend` folder in the repository
- [x] Get your backend server running and have the webpage print you a custom message!

**Comment by harshit496** [comment]
@NathanDuPont I'd like to take a first stab at this. Could you assign this to me?
